version: '3.3'
services:

  mysql:
    hostname: db
    image: 'mariadb:10.3'
    restart: always
    volumes:
      - './mysql/data:/var/lib/mysql'
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    networks:
      code-network:
        aliases:
          - db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xmx1g -Xms1g'
    networks:
      code-network:
        aliases:
          - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.0
    container_name: logstash
    volumes:
      - './logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml'
      - './logstash/pipeline:/usr/share/logstash/pipeline'
      - './logstash/lastrun:/root/.logstash_jdbc_last_run'
    ports:
      - '5001:5001'
    links:
      - elasticsearch
      - mysql
    environment:
      LS_JAVA_OPTS: '-Xmx1g -Xms1g'
    networks:
      - code-network
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    container_name: kibana
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - './kibana/config/:/usr/share/kibana/config'
    ports:
      - '5601:5601'
    links:
      - elasticsearch
    networks:
      - code-network
    depends_on:
      - elasticsearch

networks:
  code-network:
    driver: bridge
